spring.application.name=api-cd-produto
# Source - https://stackoverflow.com/q/25930191
# Posted by jimish, modified by community. See post 'Timeline' for change history
# Retrieved 2026-08-05, License - CC BY-SA 3.0

# JPA

#spring.jpa.show-sql=true

#server.port=8080

#spring.datasource.url=jdbc:mysql://localhost/varejo

#spring.datasource.driverClassName=com.mysql.jdbc.Driver

#spring.datasource.username=root

#spring.datasource.password=root



# Use one of create/update/create-update    
# DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/med?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
app.upload.dir=uploads/imagens
